### ISSUE TITLE
Hay de dividir estas clases en .pys independientes

### ISSUE THREAD

**Issue by yosbel-penate** [Bluemoonside/ProyectoEncuestaCreatividad#74]
Hay de dividir estas clases en .pys independientes

_Originally posted by @yosbel-penate in https://github.com/Bluemoonside/ProyectoEncuestaCreatividad/pull/70#discussion_r1062679792_

**Comment by EmanuelBorrajero** [comment]
que clases hay que dividir todos ponmes los nombres en especifico

**Comment by yosbel-penate** [comment]
Da click aqui

![image](https://user-images.githubusercontent.com/58090876/213749473-cf763b33-0115-4490-9b8f-0d9cbabe7d22.png)
